name: üöÄ Deploy Frontend to Apache2 VM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production


    steps:
      # ----------------- CHECKOUT -----------------
      - name: üß© Checkout c√≥digo
        uses: actions/checkout@v4

      # ----------------- NODE -----------------
      - name: ‚öô Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # ----------------- DEPENDENCIAS -----------------
      - name: üí° Instalar Angular CLI global
        run: npm install -g @angular/cli

      - name: üì¶ Instalar dependencias frontend
        run: |
          cd app-frontend
          npm install

      # ----------------- BUILD FRONTEND -----------------
      - name: üèó Build frontend
        run: |
          cd app-frontend
          ng build --configuration production --base-href /

      # ----------------- PREPARAR FRONTEND -----------------
      - name: üß© Preparar archivos frontend
        run: |
          rm -rf deploy-frontend
          mkdir deploy-frontend
          cp -r app-frontend/dist/app-frontend/browser/* deploy-frontend/
          cp app-frontend/dist/app-frontend/3rdpartylicenses.txt deploy-frontend/ || true
          cp app-frontend/dist/app-frontend/prerendered-routes.json deploy-frontend/ || true

      # ----------------- DEBUG -----------------
      - name: üßæ Ver contenido listo para deploy
        run: ls -R deploy-frontend

      # ----------------- LIMPIAR SERVER -----------------
      - name: üßπ Limpiar deploy-frontend en el servidor
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.SERVER_PORT || '22' }}
          script: |
            rm -rf /var/www/leo_site/deploy-frontend/*
            mkdir -p /var/www/leo_site/deploy-frontend

      # ----------------- SUBIR ARCHIVOS -----------------
      - name: üì§ Subir frontend al servidor
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.SERVER_PORT || '22' }}
          source: "deploy-frontend/*"
          target: "/var/www/leo_site/deploy-frontend/"
          overwrite: true

      # ----------------- FINAL -----------------
      - name: ‚öô Configurar permisos finales
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.SERVER_PORT || '22' }}
          script: |
            chmod -R 755 /var/www/leo_site/deploy-frontend
            echo "‚úî Deploy completado"
